volumes:
  auth_postgres_data: {}
  auth_postgres_data_backups: {}

services:
  postgres:
    image: postgres:14
    hostname: postgres
    ports:
      - "5430:5432"
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
      - auth_postgres_data_backups:/backups
    env_file:
      - .env

  nginx:
    build:
      context: ./nginx
      dockerfile: DockerfileLocalCerts  
    ports:
      - "5040:443"
      - "5039:80"
    extra_hosts:
      - "host.docker.internal:host-gateway"
      